services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    environment:
      - PUID=1004
      - PGID=1004
      - SERVERURL=your_vpn_server_url  # e.g., "myserver.com"
      - SERVERPORT=51820
      - PEERS=1  # number of peers (clients) to generate
      - PEERDNS=8.8.8.8  # DNS server
      - ALLOWEDIPS=0.0.0.0/0  # All traffic
    volumes:
      - ./config:/config  # Mounts a local directory `./config` to `/config` inside the container
      - /etc/wireguard  # Optionally, if you want to mount a custom directory from the host
    ports:
      - "51820:51820/udp"
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    restart: unless-stopped